site_name: Cavatappi PHP Framework
nav:
  - About: about.md
  - Packages: packages/index.md
  - Roadmap: roadmap.md
  - Walkthrough:
    - Intro: walkthrough/index.md
    - Setup: walkthrough/01-setup.md
    - Values: walkthrough/02-values.md
    - Services: walkthrough/03-services.md
    - Tests: walkthrough/04-tests.md
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
site_url: https://docs.cavatappi.dev
repo_url: https://github.com/cavatappiphp/cavatappi/
edit_uri: edit/main/docs/
copyright: >
  Cavatappi PHP Framework &copy; <a href="https://oddevan.com/">Evan Hildreth</a> and contributors. Content licensed
  under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Code samples marked for the public domain
  via <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0</a>.