site_name: Cavatappi PHP Framework
nav:
  - About: about.md
  - Packages: packages/index.md
  - Roadmap: roadmap.md
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
site_url: https://docs.cavatappi.dev
repo_url: https://github.com/cavatappiphp/cavatappi/
edit_uri: edit/main/docs/
copyright: Cavatappi PHP Framework &copy; <a href="https://oddevan.com/">Evan Hildreth</a> and contributors